services:
  todo-frontend:
    image: todo-frontend-production
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy