services:
  frontend-dev:
    image: todo-frontend-development
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000
    environment: # hot reloading: https://stackoverflow.com/a/44643246
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy